title: Discord Qada | قادة ديسكورد
logo: https://avatars.githubusercontent.com/u/125831329
description: Helping you use Discord professionally | نساعدك في استخدام ديسكورد بشكل احترافي
theme: jekyll-theme-minimal
